In [1]:
import numpy
import time
import math
import random
import matplotlib.pyplot
import sklearn.discriminant_analysis
import sklearn.naive_bayes
import warnings
warnings.filterwarnings('ignore')
from mlxtend.feature_selection import SequentialFeatureSelector as sfs

In [2]:
# create  mean and covariance 
mean1 = [-9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
mean2 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

# Create 20 by 20 CoV matrix
cov = [[3, 1, 1, 1, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 4, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 4, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 5, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 6, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0,  0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 5, 0, 0,  0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0,  0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0,  0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4,  0, 0, 2, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0],
       [0, 0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0],
       [0, 0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0],
       [0, 0, 0, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10],]

In [3]:
#Checking shape
numpy.shape(mean1) ,numpy.shape(mean2),numpy.shape(cov)

((20,), (20,), (20, 20))

In [4]:
# Make the cov sysmetric
cov = numpy.dot(cov, numpy.transpose(cov))

In [5]:
# Create 2000 by 20 dimension data
n=1000
x1 = numpy.random.multivariate_normal(mean1,cov, n)
x2 = numpy.random.multivariate_normal(mean2,cov, n)
X=numpy.concatenate((x1,x2))
X.shape

(2000, 20)

In [6]:
# Create the two class of data
n=1000
Xc1 = numpy.zeros(n)
Xc2=  numpy.ones(n)
y = numpy.concatenate((Xc1,Xc2))
numpy.shape(y)

(2000,)

### Implementing  Linear Discriminant and Naive Bayes with PCA 

In [7]:
import numpy as np
 
def PCA(X , num_components): 
    #Step-1
    X_meaned = X - np.mean(X , axis = 0)
    #Step-2
    cov_mat = np.cov(X_meaned , rowvar = False)  
    #Step-3
    eigen_values , eigen_vectors = np.linalg.eigh(cov_mat)  
    #Step-4
    sorted_index = np.argsort(eigen_values)[::-1]
    sorted_eigenvalue = eigen_values[sorted_index]
    sorted_eigenvectors = eigen_vectors[:,sorted_index]
    #Step-5
    eigenvector_subset = sorted_eigenvectors[:,0:num_components]
    #Step-6
    X_reduced = np.dot(eigenvector_subset.transpose() , X_meaned.transpose() ).transpose()
    return X_reduced

In [8]:
# Choosing PCA with five component
X_data= PCA(X,6)

In [9]:
X_data.shape

(2000, 6)

In [10]:
from sklearn.model_selection import train_test_split
# spliting training and testing sets
X_train , X_test, Y_train, Y_test = train_test_split(X_data, y, test_size=0.25, random_state = 0)


In [11]:
## Implementing LDA 
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

#### Implementing Linear Discrimination Analysis with PCA

In [12]:
LDA=LinearDiscriminantAnalysis()
starttrain_LDA=time.time()
LDA.fit(X_train,Y_train)
endtrain_LDA=time.time()
LDA_train=endtrain_LDA-starttrain_LDA

In [13]:
strattest_LDA=time.time()
y_pred=LDA.predict(X_test)
endtest_LDA=time.time()
LDA_test=endtest_LDA-strattest_LDA

In [14]:
cm=confusion_matrix(Y_test,y_pred)
print("The confusion Matrix: \n",cm)
print("The accuracy score:",accuracy_score(Y_test,y_pred))
print("Training time for LDA with PCA" ,LDA_train)
print("Testing time for LDA with PCA" , LDA_test)

The confusion Matrix: 
 [[252   2]
 [  1 245]]
The accuracy score: 0.994
Training time for LDA with PCA 0.002908468246459961
Testing time for LDA with PCA 0.0


#### Implementing Naive bayes with PCA

In [15]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
starttrain_GNB=time.time()
classifier.fit(X_train, Y_train) 
endtrain_GNB=time.time()
GNB_train=endtrain_GNB-starttrain_GNB

In [16]:
strattest_GNB=time.time()
y_pred_NB=classifier.predict(X_test)
endtest_GNB=time.time()
GNB_test=endtest_GNB-strattest_GNB

In [17]:
cm=confusion_matrix(Y_test,y_pred_NB)
print("The confusion Matrix: \n",cm)
print("The accuracy score:",accuracy_score(Y_test,y_pred_NB))
print("Training time for Naive Bayes with PCA" ,GNB_train)
print("Testing time for Naive Bayes with PCA" , GNB_test)

The confusion Matrix: 
 [[254   0]
 [  2 244]]
The accuracy score: 0.996
Training time for Naive Bayes with PCA 0.0019278526306152344
Testing time for Naive Bayes with PCA 0.0010013580322265625


### Implementing  Linear Discriminant and Naive Bayes with Forward Search Feature Selection

In [18]:
X_train,X_test,y_train,y_test= train_test_split(X, y, test_size=0.25, random_state=0)
X_train.shape,X_test.shape,y_train.shape,y_test.shape


((1500, 20), (500, 20), (1500,), (500,))

#### Implementing Linear Discrimination Analysis with Forward Search Feature Selection

In [19]:
k_features=6
LDA_FS=LinearDiscriminantAnalysis()
sfs1=sfs(LDA_FS,k_features=k_features,forward=True)
sfs1=sfs1.fit(X_train,y_train)

In [20]:
feat_cols=list(sfs1.k_feature_idx_)
print(feat_cols)

[0, 1, 2, 3, 10, 12]


In [21]:
starttrain_LDA=time.time()
LDA_FS.fit(X_train[:,feat_cols],y_train)
endtrain_LDA=time.time()
LDA_train_FS=endtrain_LDA-starttrain_LDA

In [22]:
strattest_LDA=time.time()
y_pred_FS=LDA_FS.predict(X_test[:,feat_cols])
endtest_LDA=time.time()
LDA_test_FS=endtest_LDA-strattest_LDA

In [23]:
cm=confusion_matrix(y_test,y_pred_FS)
print("The confusion Matrix: \n",cm)
print("The accuracy score:",accuracy_score(y_test,y_pred_FS)) 
print("Training time for LDA with Forward Search" ,LDA_train_FS)
print("Testing time for LDA with Forward Search" , LDA_test_FS)

The confusion Matrix: 
 [[253   1]
 [  0 246]]
The accuracy score: 0.998
Training time for LDA with Forward Search 0.0020017623901367188
Testing time for LDA with Forward Search 0.0010008811950683594


#### Implementing Naive Bayes with Forward Search Feature Selection

In [24]:

GNB_FS=GaussianNB()
sfs2=sfs(GNB_FS,k_features=k_features,forward=True)
sfs2=sfs2.fit(X_train,y_train)

In [25]:
feat_cols_GNB=list(sfs2.k_feature_idx_)
print(feat_cols_GNB)

[0, 7, 10, 12, 13, 14]


In [26]:
starttrain_GNB=time.time()
GNB_FS.fit(X_train[:,feat_cols_GNB],y_train)
endtrain_GNB=time.time()
GNB_train_FS=endtrain_GNB-starttrain_GNB

In [27]:
strattest_GNB=time.time()
y_pred_GNB=GNB_FS.predict(X_test[:,feat_cols_GNB])
endtest_GNB=time.time()
GNB_test_FS=endtest_GNB-strattest_GNB

In [28]:
cm=confusion_matrix(y_test,y_pred_GNB)
print("The confusion Matrix: \n",cm)
print("The accuracy score:",accuracy_score(y_test,y_pred_GNB)) 
print("Training time for Naive Bayes with Forward Search" ,GNB_train_FS)
print("Testing time for Naive Bayes with Forward Search" , GNB_test_FS)

The confusion Matrix: 
 [[254   0]
 [  0 246]]
The accuracy score: 1.0
Training time for Naive Bayes with Forward Search 0.000997304916381836
Testing time for Naive Bayes with Forward Search 0.0
